<span id="clerk-power-popup" style="display:none;">
    <div class="clerk-top-wrapper">
		<div class="col6 left">
			<div class="col12">
				<div class="alert alert-success">
					<?php echo Mage::helper('clerk')->__('%s was successfully added to your shopping cart.'); ?>
				</div>
			</div>

			<div class="col12">
				<div class="col4 left clerk-product-image">
					<img src="<?php echo $this->helper('catalog/image')->init($this->product, 'image')->resize(100); ?>" width="100" height="100" alt="<?php echo $this->stripTags($this->getImageLabel($this->product, 'small_image'), null, true) ?>" />
				</div>
				<div class="col8 left clerk-product-info">
					<span class="clerk-name"><?php echo $this->helper('catalog/output')->productAttribute($this->product, $this->product->getName(), 'name') ?></span>
					<?php echo $this->getLayout()->createBlock('catalog/product_price')->getPriceHtml($this->product); ?>
				</div>
			</div>
			<div class="clerk-clearer"></div>
		</div>

		<div class="col6 left">
			<div class="col12 padding10-top">
				<?php
					$url = Mage::getUrl('checkout/cart');
					$onclick = "setLocation('$url')";
					if ($url == Mage::getBaseUrl().ltrim($_SERVER['REQUEST_URI'], '/')) {
						$onclick = 'clerk_close_power_popup();';
					}
				?>
				<button type="button" onclick="<?php echo $onclick; ?>" class="button form-button clerk-to-cart"><span><span><?php echo Mage::helper('clerk')->__('View Shopping Cart'); ?></span></span></button>
			</div>
			<div class="col12 padding10">
				<table class="table">
					<tr>
						<td class="clerk-text"><?php echo Mage::helper('clerk')->__('%s products in your shopping cart', count($this->items)); ?></td>
						<td class="clerk-price"><?php echo Mage::helper('core')->currency($this->totals['subtotal']->getValue(), true, false); ?></td>
					</tr>
					<?php if (isset($totals['shipping'])) : ?>
						<tr class="clerk-shipping">
							<td class="clerk-text"><?php echo Mage::helper('clerk')->__('Shipping'); ?></td>
							<td class="clerk-price"><?php echo Mage::helper('core')->currency($this->totals['shipping']->getValue(), true, false); ?></td>
						</tr>
					<?php endif; ?>
					<tr class="clerk-total">
						<td class="clerk-text"><?php echo Mage::helper('clerk')->__('Total'); ?></td>
						<td class="clerk-price"><?php echo Mage::helper('core')->currency($this->totals['grand_total']->getValue(), true, false); ?></td>
					</tr>
				</table>
			</div>
			<div class="col12 padding10">
				<div class="col8 left">
				<?php if (Mage::getStoreConfig('clerk/features/powerstep_type') != 'landingpage') : ?>
					<button type="button" onclick="clerk_close_power_popup();" class="button form-button clerk-continue-shopping"><span><span><?php echo Mage::helper('clerk')->__('Continue Shopping'); ?></span></span></button>
				<?php endif; ?>
				</div>
				<div class="col4 left">
				<?php
					$url = $this->sidebar->getCheckoutUrl();
					$onclick = "setLocation('$url')";
					if ($url == Mage::getBaseUrl().ltrim($_SERVER['REQUEST_URI'], '/')) {
						$onclick = 'clerk_close_power_popup();';
					}
				?>
					<button type="button" onclick="<?php echo $onclick; ?>" class="button form-button clerk-to-checkout"><span><span><?php echo Mage::helper('clerk')->__('To Checkout'); ?></span></span></button>
				</div>
			</div>
		</div>
	</div>
	<div class="clerk-clearer"></div>
	<div class="clerk-results">
		<?php $templates = Mage::getStoreConfig('clerk/features/powerstep_template'); ?>
		<?php $templates = explode(',', $templates); ?>
		<?php foreach ($templates as $key => $template) : ?>
			<span class="clerk" data-template="@<?php echo trim($template); ?>" data-products="[<?php echo $this->product->getId(); ?>]" <?php if (!$key && Mage::getStoreConfig('clerk/features/powerstep_type') == 'popup') : ?>data-after-render="clerk_fire_power_popup"<?php endif; ?>></span>
		<?php endforeach; ?>
	</div>
<span>

<script type="text/javascript">
	function clerk_fire_power_popup() {
		Clerk.ui.popup('#clerk-power-popup').show();
	}
	function clerk_close_power_popup() {
		Clerk.ui.popup('#clerk-power-popup').close();
    }
</script>
