<div class="page-title">
  <h1><?php echo $this->titleText ?></h1>
</div>

<span
    id="clerk-search"
    class="clerk"
    data-template="@<?php echo $this->template ?>"
    data-offset="0"
    data-target="#clerk-search-results"
    data-after-render="_clerk_after_load_event"
    data-query="<?php echo htmlentities($_GET['q']); ?>"> 
</span>
 
<div class="category-products">
    <ul id="clerk-search-results" class="products-grid"></ul>
</div>

<div id="clerk-search-no-results" style="display: none;">
    <p class="note-msg"><?php echo $this->noResultsText ?></p>
</div>
 
<div id="clerk-search-load-more-button" style="text-align:center; display: none;">
    <button class="button"><?php echo $this->loadMoreText ?></button>
</div>
 
<script type="text/javascript">
    var total_loaded = 0;
    function _clerk_after_load_event(data) {
        total_loaded += data.response.result.length;

        // Use Clerk jQuery if needed (this is when site version is <= 1.4.3)
        $_ = useClerkjQuery() ? Clerk.iu.$ : jQuery 

        // If limit is undefined set limit to result length
        var e = $_('#clerk-search');
        if (typeof e.data('limit') === "undefined"){
        e.data('limit', data.response.result.length) 
        }

        // Setup eventhandler for loadmore button
        $_('#clerk-search-load-more-button').on('click', function() {
            e.data('offset', e.data('offset') + e.data('limit'));
            Clerk.renderBlocks('#clerk-search');
        });

        // If total is 0, show no results
        if (total_loaded == 0) {
            $_('#clerk-search-no-results').show();
        } else {
            $_('#clerk-search-no-results').hide();
        }

        // Show LoadMore button if totalloadses is not eq to hits
        if (total_loaded == data.response.hits) {
            $_('#clerk-search-load-more-button').hide();
        } else{
            $_('#clerk-search-load-more-button').show();
        }
    }
</script>
