<?php
    $publicapikey = Mage::helper('clerk')->getSetting('clerk/general/publicapikey');
    $formkey = Mage::getSingleton('core/session')->getFormKey();
?>

<script type="text/javascript">
    window.clerkAsyncInit = function() {
        Clerk.config({
            key: '<?php echo $publicapikey; ?>',
            templateFormatters: {
                form_key: function () {
                    return '<?php echo $formkey; ?>';
                }
            }
        });
    };
    (function(){
        var e = document.createElement('script'); e.type='text/javascript'; e.async = true;
        e.src = document.location.protocol + '//api.clerk.io/static/clerk.js';
        var s = document.getElementsByTagName('script')[0]; s.parentNode.insertBefore(e, s);
    })();
</script>
