<?php
/** @var Clerk_Clerk_Block_Search $this */
?>
<div id="clerk_search_block">

  <div class="page-title">
    <h1><?php echo $this->getTitleText(); ?></h1>
  </div>
  <span <?php echo $this->getSpanAttributes(); ?>></span>

  <div class="category-products">
      <ul id="<?php echo $this->getTargetId(); ?>" class="products-grid"></ul>
  </div>

  <div id="clerk-search-no-results" style="display: none;">
      <p class="note-msg"><?php echo $this->getNoResultsText(); ?></p>
  </div>

  <div id="clerk-search-load-more-button" style="text-align:center; display: none;">
      <button class="button"><?php echo $this->getLoadMoreText(); ?></button>
  </div>

</div>
<script type="text/javascript">
    var total_loaded = 0;
    function _clerk_after_load_event(data) {
        total_loaded += data.response.result.length;

        // Use Clerk jQuery if needed (this is when site version is <= 1.4.3)
        $_ = useClerkjQuery() ? Clerk.ui.$ : jQuery

        // If limit is undefined set limit to result length
        var e = $_('#clerk-search');
        if (typeof e.data('limit') === "undefined"){
        e.data('limit', data.response.result.length)
        }

        // Setup eventhandler for loadmore button
        $_('#clerk-search-load-more-button').on('click', function() {
            e.data('offset', e.data('offset') + e.data('limit'));
            Clerk.renderBlocks('#clerk-search');
            $_('#clerk-search-load-more-button').off();
        });

        // If total is 0, show no results
        if (total_loaded == 0) {
            $_('#clerk-search-no-results').show();
        } else {
            $_('#clerk-search-no-results').hide();
        }

        // Show LoadMore button if totalloadses is not eq to hits
        if (total_loaded == data.response.hits) {
            $_('#clerk-search-load-more-button').hide();
        } else{
            $_('#clerk-search-load-more-button').show();
        }
    }
</script>
