<?php
/** @var Clerk_Clerk_Block_Tracking $this */

$baseCurrencyCode = Mage::app()->getStore()->getBaseCurrencyCode();
$currentCurrencyCode = Mage::app()->getStore()->getCurrentCurrencyCode();
$currentCurrencySymbol = Mage::app()->getLocale()->currency($currentCurrencyCode)->getSymbol();
$rates = Mage::getModel('directory/currency')->getCurrencyRates($baseCurrencyCode, $currentCurrencyCode);
?>
<script type="text/javascript">
    (function(w,d){
        var e=d.createElement('script');e.type='text/javascript';e.async=true;
        e.src=(d.location.protocol=='https:'?'https':'http')+'://cdn.clerk.io/clerk.js';
        var s=d.getElementsByTagName('script')[0];s.parentNode.insertBefore(e,s);
        w.__clerk_q=w.__clerk_q||[];w.Clerk=w.Clerk||function(){w.__clerk_q.push(arguments)};
    })(window,document);
    Clerk('config', {
        key: '<?php echo $this->getPublicKey(); ?>',
        collect_email: <?php echo $this->collectEmails() ? 'true' : 'false'; ?>,
        language: '<?php echo str_replace('auto_','',Mage::helper('clerk')->getSetting('clerk/general/lang')) ?>',
        formatters: {
            form_key: function () {
                return '<?php echo $this->getFormKey(); ?>';
            },
            <?php if ($rates && isset($rates[$currentCurrencyCode])) : ?>
            price_in_currency: function(price) {
                price =  Math.round(price * 100) / 100;
                var price_converted = Math.round((price * <?php echo (float)$rates[$currentCurrencyCode]; ?>) * 100) / 100;
                var retVal = <?php echo json_encode($currentCurrencySymbol); ?> + ' ' + price_converted.toFixed(2).toString();

                return retVal;
            }
            <?php endif; ?>
        }
    });
</script>
